version: "3.8"
services:
  algod:
    image: ghcr.io/voinetwork/voi-node-participation:pr-7
    environment:
      TELEMETRY_NAME: ${VOINETWORK_TELEMETRY_NAME}
      VOINETWORK_PROFILE: ${VOINETWORK_PROFILE}
      VOINETWORK_NETWORK: ${VOINETWORK_NETWORK}
      VOINETWORK_GENESIS: ${VOINETWORK_GENESIS}
      VOINETWORK_CATCHUP: ${VOINETWORK_CATCHUP}
    logging:
      driver: "local"
    volumes:
      - /var/lib/voi/algod/data:/algod/data/:rw
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - notification
  shepherd:
    image: containrrr/shepherd
    environment:
      RUN_ONCE_AND_EXIT: "true"
      ROLLBACK_ON_FAILURE: "true"
      IMAGE_AUTOCLEAN_LIMIT: "5"
    logging:
      driver: "local"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 0
      restart_policy:
        condition: none
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 */4 * * *
        - swarm.cronjob.skip-running=true
      placement:
        constraints:
          - node.role == manager
  scheduler:
    image: ghcr.io/voinetwork/swarm-cronjob:edge
    logging:
      driver: "local"
    environment:
      - "TZ=UTC"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  notification:
